MAP_VERSAO_LABEL_FIELD = {
    "receita_carteira": "Receita (Carteira)",
    "receita_estoque": "Receita (Estoque)",
    "decoracao": "Decoração",
    "tir_real": "TIR REAL",
    "tir_nominal": "TIR NOMINAL",
    "receita_vendida_pre_chaves": "Receita Vendida Pré Chaves",
    "receita_vendida_pos_chaves": "Receita Vendida Pós Chaves",
    "estoque_pre_chaves": "Estoque Pré Chaves",
    "estoque_pos_chaves": "Estoque Pós Chaves",
    "financiamento_banco": "Financiamento Banco",
    "divida_hoje": "Dívida Hoje",
    "ic": "IC",
    "ic_fp": "IC FP",
    "ltv": "LTV",
    "inadimplencia": "Inadimplência",
    "unidades_inadimplentes": "Unidades Inadimplentes",
    "razao_inadimplente_vendido": "% inadimplente Vendido",
    "razao_vendido": "% Vendido",
    "area_estoque": "Area Estoque",
    "razao_lucro_area_media_vendas": "R$/m² Médio Vendas",
    "razao_lucro_area_estoque": "R$/m² Estoque",
    "razao_custo_area_liquidacao_divida": "R$/m² para liquidar dívida",
    "distribuicao_mes": "Distribuição Mes",
    "distribuicao_acumulada": "Distribuição Acumulada",
    "projetado_a_distribuir": "Projetado a Distribuir",
    "saldo_incorporador": "Saldo Incorporador",
    "razao_custo_area_para_zerar_saldo_incorporador": "R$/m² para zerar saldo incorporador",
    "inicio_cash_sweep": "Início Cash Sweep",
    "data_base": "Data Base",
}
